name: Build Android APK

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - build-apk  # Push to this branch triggers the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Clean Flutter Cache
        run: flutter pub cache repair

      - name: Upgrade Dependencies
        run: flutter pub upgrade --major-versions

      - name: Get Dependencies
        run: flutter pub get

      - name: Grant Execute Permission to Gradle
        run: chmod +x android/gradlew

      - name: Clean Gradle Cache
        run: cd android && ./gradlew clean

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk